- type: entity
  name: .20 pistol magazine box
  parent: BoxCardboard
  id: LPPBox20Pistol
  description: 4 pistol mags of .20
  components:
  - type: StorageFill
    contents:
      - id: LPPMagazinePistolPF20lethal
        amount: 4

- type: entity
  name: 5.56 magazine box
  parent: BoxCardboard
  id: LPPBoxMagazineRifleM4A1Lethal
  description: 4 rifle mags of 5.56
  components:
  - type: StorageFill
    contents:
      - id: LPPMagazineRifleM4A1Lethal
        amount: 4
