# SPDX-FileCopyrightText: 2021 Paul <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2022 0x6273 <0x40@keemail.me>
# SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2022 Vera Aguilera Puerto <gradientvera@outlook.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Jezithyr <jezithyr@gmail.com>
# SPDX-FileCopyrightText: 2024 Matt <psykzz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if we are attempting to run on the master branch
      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'space-wizards/space-station-14'}}
      run: exit 1

#    - name: Install dependencies
#      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    - name: Download parts
      if: ${{ vars.SECRETSLINK != '' }}
      run: |
        git clone ${{ secrets.SECRETS }}
        mv NewSecrets/PResources/PPrototypes Resources/Prototypes/
        mv NewSecrets/PResources/PTextures Resources/Textures/
        mv NewSecrets/PShared Content.Shared/PShared
        mv NewSecrets/PServer Content.Server/PServer
        mv NewSecrets/PClient Content.Client/PClient

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x
      env:
        DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet

    - name: Set DOTNET_ROOT and PATH
      run: |
        echo "DOTNET_ROOT=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
        echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH

    - name: Check .NET installation
      run: dotnet --info

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
        FORK_ID: ${{ vars.FORK_ID }}

#    - name: Publish changelog
#      run: Tools/actions_changelogs_since_last_run.py
#      env:
#        CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
#        CHANGELOG_WEBHOOK: ${{ secrets.CHANGELOG_WEBHOOK }}
#        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

    #    - name: Publish changelog (RSS)
    #      continue-on-error: true
    #      run: Tools/actions_changelog_rss.py
    #      env:
    #        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}

    - uses: geekyeggo/delete-artifact@v5
      if: always()
      with:
        name: build
